DROP DATABASE IF EXISTS PROJETINHO_TODOLIST;
CREATE DATABASE PROJETINHO_TODOLIST;
USE PROJETINHO_TODOLIST;

CREATE TABLE TODO_INFO(
    INFO_TODO_TITLE VARCHAR(100) NOT NULL,
    INFO_TODO_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    INFO_TODO_RESPONSIBLE VARCHAR(45) NOT NULL,
    INFO_TODO_STATUS BOOLEAN NOT NULL
);